### ISSUE TITLE
ERR unknown command 

### ISSUE THREAD

**Issue by pooria-noruzi** [redis-developer/redis-om-dotnet-skeleton-app#6]
Hi , i tried many way to  setup redis om on my project , but each time get error with : 'ERR unknown command 'any things !!!'

I run redis on docker desktop and set any data with :  Redis Insight , when i run your sample program get this error :

StackExchange.Redis.RedisServerException: 'ERR unknown command 'FT._LIST''

in my project when i want to set a json data i get "ERR unknown command 'JSON.SET'"  , just connection.execute("ping") return me PONG without error !

please help me !

**Comment by iivanmendozaa** [comment]
Hey!,

Did you have installed the RedisStack Image from https://hub.docker.com/r/redis/redis-stack, you should install this to get all packages including RedisJSON, RedisSearch, and so on.

**Comment by slorello89** [comment]
definitely an incorrect redis-version being used here. use `redis-stack` / `redis-stack-server`
